[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Michael Rahlff <post@m-rahlff.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5"
rand = "0.8.4"
array2d = "0.2.1"
